name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      v:
        description: 'v'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [A, B, C, D, E]
    steps:
      - uses: actions/checkout@v3
        
      - name: Run a multi-line script
        run: |
          chmod +x lite-linux-amd64
          while :; do ./lite-linux-amd64 --config config.json --test ${{ github.event.inputs.v }}; done
